/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_Helloworld */

#ifndef _Included_JNI_Helloworld
#define _Included_JNI_Helloworld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_Helloworld
 * Method:    printHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_Helloworld_printHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
