SELECT YEAR( A.SALES_DATE ) AS YEAR, MONTH( A.SALES_DATE ) AS MONTH, B.GENDER AS GENDER, COUNT( * ) AS USERS
FROM( SELECT USER_ID AS USER_ID, SALES_DATE AS SALES_DATE FROM ONLINE_SALE GROUP BY YEAR( SALES_DATE ), MONTH( SALES_DATE ),USER_ID) A,
    ( SELECT USER_ID AS ID, GENDER AS GENDER FROM USER_INFO WHERE GENDER IS NOT NULL ) B
WHERE A.USER_ID = B.ID
GROUP BY YEAR( A.SALES_DATE ) , MONTH( A.SALES_DATE ), B.GENDER
ORDER BY YEAR( A.SALES_DATE ) , MONTH( A.SALES_DATE ), B.GENDER ASC;